### ISSUE TITLE
stuck at the last 3rd step?

### ISSUE THREAD

**Issue by zqkgo** [itchyny/maze#5]
can't move to the last step, almost every time stuck at the last 3rd step.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/14950473/235666941-03523089-1303-4a1f-a534-d16ca9a61bb3.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/14950473/235667149-b26c46b3-9edc-4a54-8b84-aa86ef7fc258.png">

**Comment by itchyny** [comment]
Thanks, this is a regression of ef4f8dba6c85b195a23e36736e9a7ed91211046c, and fixed now.
